export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const ADMIN_SIGNUP_REQUEST = "ADMIN_SIGNUP_REQUEST";

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";

export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
